/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.tubanquito.ui;

import java.awt.FileDialog;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.itson.tubanquito.entities.Account;
import mx.itson.tubanquito.entities.Transactions;
import mx.itson.tubanquito.enums.TypeTransaction;

/**
 *
 * @author rosagabriela
 */

 //the main class on the code
public class Main extends javax.swing.JFrame {

    private Account currentAccount;
    private double balanceFromJsonFile;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        lblTotal2.setText("0.00");
        this.balanceFromJsonFile = 0.0;
    
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlTittle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTransactions = new javax.swing.JTable();
        btnFile = new javax.swing.JButton();
        lblName2 = new javax.swing.JLabel();
        pnlState2 = new javax.swing.JPanel();
        lblName1 = new javax.swing.JLabel();
        lblAccountNumber1 = new javax.swing.JLabel();
        lblCurrency1 = new javax.swing.JLabel();
        lblAccountNumber2 = new javax.swing.JLabel();
        pnlTittle2 = new javax.swing.JPanel();
        lblTittle2 = new javax.swing.JLabel();
        lblCurrency2 = new javax.swing.JLabel();
        pnlTittle3 = new javax.swing.JPanel();
        lblTitle3 = new javax.swing.JLabel();
        pnlState3 = new javax.swing.JPanel();
        lblClientCode1 = new javax.swing.JLabel();
        lblId1 = new javax.swing.JLabel();
        lblClientCode2 = new javax.swing.JLabel();
        lblId2 = new javax.swing.JLabel();
        pnlState4 = new javax.swing.JPanel();
        lblAddress1 = new javax.swing.JLabel();
        lblCity1 = new javax.swing.JLabel();
        lblZipCode1 = new javax.swing.JLabel();
        pnlTittle4 = new javax.swing.JPanel();
        lblTitle4 = new javax.swing.JLabel();
        lblAddress2 = new javax.swing.JLabel();
        lblCity2 = new javax.swing.JLabel();
        lblZipCode2 = new javax.swing.JLabel();
        btnCalculateDR = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtDailyRate = new javax.swing.JTextField();
        lblTotal2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("...");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTittle.setBackground(new java.awt.Color(0, 51, 255));
        pnlTittle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblTitle.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Payroll Account");

        javax.swing.GroupLayout pnlTittleLayout = new javax.swing.GroupLayout(pnlTittle);
        pnlTittle.setLayout(pnlTittleLayout);
        pnlTittleLayout.setHorizontalGroup(
            pnlTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTittleLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnlTittleLayout.setVerticalGroup(
            pnlTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTittleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tblTransactions.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tblTransactions.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        tblTransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Description", "Reference", "Credit", "Debit", "Balance"
            }
        ));
        tblTransactions.setToolTipText("");
        tblTransactions.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(tblTransactions);

        btnFile.setBackground(new java.awt.Color(0, 51, 255));
        btnFile.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnFile.setForeground(new java.awt.Color(255, 255, 255));
        btnFile.setText("Select file");
        btnFile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileActionPerformed(evt);
            }
        });

        lblName2.setBackground(new java.awt.Color(153, 153, 153));
        lblName2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblName2.setForeground(new java.awt.Color(51, 51, 51));
        lblName2.setText("...");

        pnlState2.setBackground(new java.awt.Color(51, 102, 255));

        lblName1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblName1.setForeground(new java.awt.Color(255, 255, 255));
        lblName1.setText("Name");

        lblAccountNumber1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblAccountNumber1.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountNumber1.setText("Account number");

        lblCurrency1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblCurrency1.setForeground(new java.awt.Color(255, 255, 255));
        lblCurrency1.setText("Currency");

        javax.swing.GroupLayout pnlState2Layout = new javax.swing.GroupLayout(pnlState2);
        pnlState2.setLayout(pnlState2Layout);
        pnlState2Layout.setHorizontalGroup(
            pnlState2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlState2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlState2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlState2Layout.createSequentialGroup()
                        .addGroup(pnlState2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAccountNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCurrency1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlState2Layout.setVerticalGroup(
            pnlState2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlState2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAccountNumber1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCurrency1)
                .addContainerGap())
        );

        lblAccountNumber2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblAccountNumber2.setForeground(new java.awt.Color(51, 51, 51));
        lblAccountNumber2.setText("...");

        pnlTittle2.setBackground(new java.awt.Color(0, 51, 255));

        lblTittle2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblTittle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTittle2.setText("Statement of Account:");

        javax.swing.GroupLayout pnlTittle2Layout = new javax.swing.GroupLayout(pnlTittle2);
        pnlTittle2.setLayout(pnlTittle2Layout);
        pnlTittle2Layout.setHorizontalGroup(
            pnlTittle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTittle2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTittle2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
        );
        pnlTittle2Layout.setVerticalGroup(
            pnlTittle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTittle2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblCurrency2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblCurrency2.setForeground(new java.awt.Color(51, 51, 51));
        lblCurrency2.setText("...");

        pnlTittle3.setBackground(new java.awt.Color(0, 51, 255));
        pnlTittle3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblTitle3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblTitle3.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle3.setText("Information:");

        javax.swing.GroupLayout pnlTittle3Layout = new javax.swing.GroupLayout(pnlTittle3);
        pnlTittle3.setLayout(pnlTittle3Layout);
        pnlTittle3Layout.setHorizontalGroup(
            pnlTittle3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTittle3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle3, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        pnlTittle3Layout.setVerticalGroup(
            pnlTittle3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlState3.setBackground(new java.awt.Color(51, 102, 255));

        lblClientCode1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblClientCode1.setForeground(new java.awt.Color(255, 255, 255));
        lblClientCode1.setText("Client code");

        lblId1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblId1.setForeground(new java.awt.Color(255, 255, 255));
        lblId1.setText("Taxpayer-ID");

        javax.swing.GroupLayout pnlState3Layout = new javax.swing.GroupLayout(pnlState3);
        pnlState3.setLayout(pnlState3Layout);
        pnlState3Layout.setHorizontalGroup(
            pnlState3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlState3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlState3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClientCode1)
                    .addComponent(lblId1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        pnlState3Layout.setVerticalGroup(
            pnlState3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlState3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClientCode1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblId1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblClientCode2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblClientCode2.setForeground(new java.awt.Color(51, 51, 51));
        lblClientCode2.setText("...");

        lblId2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblId2.setForeground(new java.awt.Color(51, 51, 51));
        lblId2.setText("...");

        pnlState4.setBackground(new java.awt.Color(51, 102, 255));

        lblAddress1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblAddress1.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress1.setText("Address");

        lblCity1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblCity1.setForeground(new java.awt.Color(255, 255, 255));
        lblCity1.setText("City");

        lblZipCode1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblZipCode1.setForeground(new java.awt.Color(255, 255, 255));
        lblZipCode1.setText("Zip Code");

        javax.swing.GroupLayout pnlState4Layout = new javax.swing.GroupLayout(pnlState4);
        pnlState4.setLayout(pnlState4Layout);
        pnlState4Layout.setHorizontalGroup(
            pnlState4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlState4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlState4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAddress1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblZipCode1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        pnlState4Layout.setVerticalGroup(
            pnlState4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlState4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddress1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCity1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblZipCode1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTittle4.setBackground(new java.awt.Color(0, 51, 255));

        lblTitle4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblTitle4.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle4.setText("Address:");

        javax.swing.GroupLayout pnlTittle4Layout = new javax.swing.GroupLayout(pnlTittle4);
        pnlTittle4.setLayout(pnlTittle4Layout);
        pnlTittle4Layout.setHorizontalGroup(
            pnlTittle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTittle4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        pnlTittle4Layout.setVerticalGroup(
            pnlTittle4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblAddress2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblAddress2.setForeground(new java.awt.Color(51, 51, 51));
        lblAddress2.setText("...");

        lblCity2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblCity2.setForeground(new java.awt.Color(51, 51, 51));
        lblCity2.setText("...");

        lblZipCode2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblZipCode2.setForeground(new java.awt.Color(51, 51, 51));
        lblZipCode2.setText("...");

        btnCalculateDR.setBackground(new java.awt.Color(51, 102, 255));
        btnCalculateDR.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnCalculateDR.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculateDR.setText("Calculate");
        btnCalculateDR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateDRActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jLabel4.setBackground(new java.awt.Color(0, 51, 255));
        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("         Interest rate");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        txtDailyRate.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtDailyRate.setForeground(new java.awt.Color(51, 51, 51));
        txtDailyRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDailyRateActionPerformed(evt);
            }
        });

        lblTotal2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblTotal2.setForeground(new java.awt.Color(51, 51, 51));
        lblTotal2.setText("...");

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFile, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDailyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCalculateDR, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlState3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClientCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(139, 139, 139))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlState4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblZipCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCity2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(pnlTittle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(312, 312, 312)
                                .addComponent(pnlTittle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlState2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAccountNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCurrency2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(291, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlTittle3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlTittle4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTittle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTittle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlState2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblName2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAccountNumber2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCurrency2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlTittle3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblClientCode2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblId2)
                                        .addGap(6, 6, 6))
                                    .addComponent(pnlState3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlTittle4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlState4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblAddress2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblCity2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblZipCode2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(158, 158, 158)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnFile)
                                            .addComponent(btnCalculateDR))
                                        .addGap(20, 20, 20))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtDailyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileActionPerformed
        FileDialog fileDialog = new FileDialog(this, "Seleccionar Archivo", FileDialog.LOAD);
                fileDialog.setVisible(true);

                String directory = fileDialog.getDirectory();
                String filename = fileDialog.getFile();

                /* an if statement was created to check if the variale filename is not null.
                if the variable is not null, it means that a file was selected. duh 
                */
                if (filename != null) {
                    File selectedFile = new File(directory, filename);
                    try (BufferedReader reader = new BufferedReader(new FileReader(selectedFile))) {
                        StringBuilder content = new StringBuilder();
                        String line;
                        while ((line = reader.readLine()) != null) {
                            content.append(line).append("\n");
                        }
                        String contenido = content.toString();

                        Account a = Account.deserialize(contenido);

                        lblName2.setText(a.getAccountHolder().getName());
                        lblAccountNumber2.setText(a.getAccountNumber());
                        lblCurrency2.setText(a.getCurrency());
                        lblClientCode2.setText(String.valueOf(a.getAccountHolder().getCode()));
                        lblId2.setText(a.getAccountHolder().getTaxpayerId());
                        lblAddress2.setText(a.getAccountHolder().getAddress());
                        lblCity2.setText(a.getAccountHolder().getCity());
                        lblZipCode2.setText(String.valueOf(a.getAccountHolder().getZipCode()));

                        DefaultTableModel model = (DefaultTableModel) tblTransactions.getModel();
                        model.setRowCount(0);

                        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                        
                        /* We declare a list called 'lista' that contains all the transactions
                        obtained from the 'Account' object 
                        */
                        List<Transactions> lista = a.getTransactions();
                        
                        /* The transactions are sorted by date from oldest to newest
                        using the sort method. The method receives a Comparator that compares the 'date' field.
                        */
                        lista.sort(Comparator.comparing(Transactions::getDate));
                        double balance=0;
                        
                        /* 
                        A for loop was created to iterate through the list of "Transactions" contained in the objetc a,
                        which is an instance of the "Account" class.
                        Inside the looop two variables were declared "credit" and "debit". These are used to display
                        the transaction amount in the correct column depending on the transaction type.
                        */
                        for(Transactions t : a.getTransactions()){
                            String credit="";
                            String debit="";
                            if(t.getType()== TypeTransaction.CREDIT){
                                credit= String.valueOf(t.getAmount());
                                balance -= t.getAmount();

                                /*
                                An "if else" is used to evaluate the type of eache transaction.
                                */
                                } else if (t.getType()==TypeTransaction.DEBIT){
                                    debit= String.valueOf(t.getAmount());
                                    balance += t.getAmount();
                                    }
                                    model.addRow(new Object[] {
                                        dateFormat.format(t.getDate()),
                                        t.getDescription(),
                                        t.getReference(),
                                        credit,
                                        debit,
                                        String.format("%.2f", balance)
                                    });
                        }

                    } catch (IOException e) {
                        e.printStackTrace();
                        // if you want to show an error message, you can do it here
                    }
                    
            try {

            if (fileDialog.getFile() == null) {
                this.currentAccount = null;
                this.balanceFromJsonFile = 0.0;
                lblTotal2.setText("0.00");
                // Clear other labels if necessary (name, account, etc)
                lblName2.setText("...");
                return;
            }

            StringBuilder content = new StringBuilder();
            try (BufferedReader reader = new BufferedReader(new FileReader(selectedFile))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    content.append(line).append("\n");
                }
            }

            String jsonContent = content.toString();
            this.currentAccount = Account.deserialize(jsonContent); // Use deserialize

            if (this.currentAccount == null) {
                JOptionPane.showMessageDialog(this, "Error al cargar el archivo JSON.", "Error", JOptionPane.ERROR_MESSAGE);
                this.balanceFromJsonFile = 0.0;
                return;
            }

            // Poblar información básica del titular (opcional, pero útil)
            if (this.currentAccount.getAccountHolder() != null) {
                lblName2.setText(this.currentAccount.getAccountHolder().getName());
                lblAccountNumber2.setText(this.currentAccount.getAccountNumber());
            } else {
                 lblName2.setText("N/A");
                 lblAccountNumber2.setText("N/A");
            }


            // Calculate balance directly from JSON transactions
            this.balanceFromJsonFile = 0.0;
            if (this.currentAccount.getTransactions() != null) {
                for (Transactions tx : this.currentAccount.getTransactions()) {
                    if (tx.getAmount() == null) continue; // Skip if no amount

                    if (tx.getType() == TypeTransaction.DEBIT) { // DEBIT (type 1) addition
                        this.balanceFromJsonFile += tx.getAmount();
                    } else if (tx.getType() == TypeTransaction.CREDIT) { // CREDIT (type 2) subtraction
                        this.balanceFromJsonFile -= tx.getAmount();
                    }
                }
            }
            

            lblTotal2.setText("0.00"); //Ready for calculation with the button

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error reading file: " + ex.getMessage(), "File Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "An error occurred: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
}

    }//GEN-LAST:event_btnFileActionPerformed

    private void btnCalculateDRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateDRActionPerformed
       
            if (this.currentAccount == null || this.currentAccount.getTransactions() == null || this.currentAccount.getTransactions().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Upload a file with transactions first.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    double dailyRateFromInput;
    try {
        String inputText = txtDailyRate.getText().trim();
        if (inputText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter a daily interest rate (Example. 0.01 for 0.01%).", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // We assume the user enters a daily percentage. We convert it to a decimal
        dailyRateFromInput = Double.parseDouble(inputText) / 100.0; 

        if (dailyRateFromInput < 0) {
            JOptionPane.showMessageDialog(this, "The rate cannot be negative.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid rate.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    List<Transactions> transactions = new ArrayList<>(this.currentAccount.getTransactions());
    // "Ensure" that they are sorted by date
    transactions.sort(Comparator.comparing(Transactions::getDate, Comparator.nullsLast(Date::compareTo)));

    double currentEffectiveBalance = 0.0; // Balance after each transaction
    double totalInterestEarned = 0.0;
    Date lastTransactionDate = null; 

    // For convenience, it is assumed that the balance is 0 before the first transaction

    for (int i = 0; i < transactions.size(); i++) {
        Transactions tx = transactions.get(i);
        if (tx.getDate() == null || tx.getAmount() == null) continue;

        // Calculate interest from the last transaction to the current one
        if (lastTransactionDate != null && currentEffectiveBalance > 0) {
            long diffInMillis = tx.getDate().getTime() - lastTransactionDate.getTime();
            int daysBetween = (int) TimeUnit.MILLISECONDS.toDays(diffInMillis);

            if (daysBetween > 0) {
                double interestForPeriod = 0;
                
                double balanceBeforeInterest = currentEffectiveBalance;
                currentEffectiveBalance = this.currentAccount.calculateBalanceWithDailyInterest(balanceBeforeInterest, dailyRateFromInput, daysBetween);
                interestForPeriod = currentEffectiveBalance - balanceBeforeInterest;
                
                totalInterestEarned += interestForPeriod;
                currentEffectiveBalance += interestForPeriod; // Add interest to the balance
            }
        }

        // Apply current transaction
        if (tx.getType() == TypeTransaction.DEBIT) { // Add to balance
            currentEffectiveBalance += tx.getAmount();
        } else if (tx.getType() == TypeTransaction.CREDIT) { // Subtraction from balance
            currentEffectiveBalance -= tx.getAmount();
        }
        
        lastTransactionDate = tx.getDate();
    }

     if (lastTransactionDate != null && currentEffectiveBalance > 0) {
         long diffInMillis = new Date().getTime() - lastTransactionDate.getTime(); // new Date() is "today"
         int daysSinceLast = (int) TimeUnit.MILLISECONDS.toDays(diffInMillis);
         if (daysSinceLast > 0) {
             double interestForPeriod = currentEffectiveBalance * dailyRateFromInput * daysSinceLast;
             totalInterestEarned += interestForPeriod;
             currentEffectiveBalance += interestForPeriod;
         }
     }

    lblTotal2.setText(String.format("Accrued interest.: %.2f | Final Balance: %.2f", totalInterestEarned, currentEffectiveBalance));

    }//GEN-LAST:event_btnCalculateDRActionPerformed

    private void txtDailyRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDailyRateActionPerformed
        double dailyRate = Double.parseDouble(txtDailyRate.getText());
    }//GEN-LAST:event_txtDailyRateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculateDR;
    private javax.swing.JButton btnFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAccountNumber1;
    private javax.swing.JLabel lblAccountNumber2;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblAddress2;
    private javax.swing.JLabel lblCity1;
    private javax.swing.JLabel lblCity2;
    private javax.swing.JLabel lblClientCode1;
    private javax.swing.JLabel lblClientCode2;
    private javax.swing.JLabel lblCurrency1;
    private javax.swing.JLabel lblCurrency2;
    private javax.swing.JLabel lblId1;
    private javax.swing.JLabel lblId2;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel lblTittle2;
    private javax.swing.JLabel lblTotal2;
    private javax.swing.JLabel lblZipCode1;
    private javax.swing.JLabel lblZipCode2;
    private javax.swing.JPanel pnlState2;
    private javax.swing.JPanel pnlState3;
    private javax.swing.JPanel pnlState4;
    private javax.swing.JPanel pnlTittle;
    private javax.swing.JPanel pnlTittle2;
    private javax.swing.JPanel pnlTittle3;
    private javax.swing.JPanel pnlTittle4;
    private javax.swing.JTable tblTransactions;
    private javax.swing.JTextField txtDailyRate;
    // End of variables declaration//GEN-END:variables
}
